project_id = "wuquclmippzuejqbcksl"

[functions.seed-demo-data]
verify_jwt = false

[functions.analyze_call]
verify_jwt = true

[functions.analyze-call]
verify_jwt = true

[functions.edit-recap-email]
verify_jwt = true
